# Generated by Django 5.0.6 on 2024-05-22 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_typeproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='portfolio.typeproject'),
        ),
    ]
