# Generated by Django 5.0.6 on 2024-05-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_type'),
    ]

    operations = [
    ]
