# Generated by Django 5.0.6 on 2024-05-24 07:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_typetag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeproject',
            options={'verbose_name': 'Typ Projektu', 'verbose_name_plural': 'Typy Projektu'},
        ),
        migrations.AlterModelOptions(
            name='typetag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tagy'},
        ),
        migrations.AlterModelOptions(
            name='typeurl',
            options={'verbose_name': 'Typ URL', 'verbose_name_plural': 'Typy URL'},
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='portfolio.typetag', verbose_name='Tagy'),
        ),
        migrations.AlterField(
            model_name='typetag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'bílá'), ('#000000', 'černá'), ('#FF0000', 'červená'), ('#00FF00', 'zelená'), ('#0000FF', 'modrá'), ('#FFFF00', 'žlutá')]),
        ),
    ]
