# Generated by Django 5.0.6 on 2024-05-24 08:03

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_typeproject_options_alter_typetag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, max_length=5000, null=True, verbose_name='Project Description'),
        ),
    ]
