# Generated by Django 5.0.6 on 2024-05-24 08:47
import random

from django.db import migrations

def insert_data(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    TypeProject = apps.get_model('portfolio', 'TypeProject')
    type_obj = TypeProject.objects.first()
    for index in range(3,5000):
        Project.objects.create(
            name=f'Project {index}',
            description=f'',
            logo=f'static/images/000022604248_po.jpg',
            url=f'https://project_{index}.com',
            type=type_obj
        )

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_project_description'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
