# Generated by Django 5.0.6 on 2024-05-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0012_auto_20240524_1047"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=1000, verbose_name="Text")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="portfolio.typetag",
                verbose_name="Tagy",
            ),
        ),
    ]
